# Generated by Django 6.0 on 2025-12-28 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AndroidApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='android/app_files/')),
                ('description', models.TextField()),
                ('is_latest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AppRasCalck',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=50)),
                ('file', models.FileField(upload_to='media/app_files/')),
                ('description', models.TextField()),
                ('is_latest', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='UserPro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=50)),
                ('is_pro', models.BooleanField(default=False)),
                ('pro_expiration_date', models.DateField(blank=True, null=True)),
                ('secret_key', models.CharField(default='061336', max_length=6)),
            ],
        ),
    ]
