# Generated by Django 6.0 on 2026-01-17 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_adm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='secret_key',
            field=models.CharField(default='978498', max_length=6),
        ),
    ]
