# Generated by Django 6.0 on 2026-01-29 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_adm', '0006_alter_userpro_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='secret_key',
            field=models.CharField(default='469109', max_length=6),
        ),
    ]
