# Generated by Django 6.0 on 2026-01-30 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_adm', '0009_alter_userpro_secret_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpro',
            name='secret_key',
            field=models.CharField(default='486717', max_length=6),
        ),
    ]
