# Generated by Django 6.0 on 2026-01-29 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ErrorLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('error_type', models.TextField()),
                ('version', models.CharField(max_length=50)),
                ('source', models.CharField(max_length=200)),
            ],
        ),
    ]
