# Generated by Django 6.0 on 2026-01-29 17:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('error_db', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='errorlog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
